//Each new term in the Fibonacci sequence is generated by adding the previous two 
//terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed 
//four million, find the sum of the even-valued terms.
var firstNum = 1;
var secondNum = 2;
var fibNum = 0;
var sumOfEvens = 0;
var maxValue = 4000000;

for (i = 1; i < 10; i++)
{
	if (secondNum % 2 === 0)
	{
		sumOfEvens += secondNum;
	}

	console.log("The sum of the evens thus far is " + sumOfEvens);

	fibNum = firstNum + secondNum;
	firstNum = secondNum;
	secondNum = fibNum;
}